--INSERT INTO TBL_DISCOUNT (id, shop, shoptype, description, active, stampModifier, stampModified) 
INSERT INTO TBL_DISCOUNT VALUES (100, 'STAR QUIDS CAFE', 'COFEE CHAIN', 'DISCOUNT APPLIES ON CAFEINATED COLD BEVERAGES ONLY', 'TURE', 'dbmngr@thiscounts.com', '1522077777');
INSERT INTO TBL_DISCOUNT VALUES (101, 'ZAIRA', 'CLOTHING SHOP', 'DISCOUNT APPLIES ON ALL THE PRODUCTS BUT UNDERCLOTHES', 'TURE', 'dbmngr@thiscounts.com', '1522077888');
INSERT INTO TBL_DISCOUNT VALUES (102, 'YOGO', 'ICECREAM SHOP', 'DISCOUNT APPLIES ON ALL THE DAIRY PRODUCTS', 'TURE', 'dbmngr@thiscounts.com', '1522077999');

--INSERT INTO TBL_COMPANY (id, name, active, stampModifier, stampModified) 
INSERT INTO TBL_COMPANY VALUES (100, 'THISCOUNTS CO', 'TURE', 'dbmngr@thiscounts.com', '1522088444');
INSERT INTO TBL_COMPANY VALUES (101, 'GLOBANT', 'TURE', 'dbmngr@thiscounts.com', '1522088333');
INSERT INTO TBL_COMPANY VALUES (101, 'NICO BOXING KING', 'FALSE', 'dbmngr@thiscounts.com', '1522088111');

